# Generated by Django 5.2.5 on 2025-09-16 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.TextField()),
                ('street_address2', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state_province', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('country', models.TextField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost_amount', models.FloatField(null=True)),
                ('estimated_cost_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.currency')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.objecttype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.address')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('birth_date', models.DateField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons_living_on_it', to='organization.address')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_exchanges', to='organization.object')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.objectpasstype')),
                ('new_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects_received', to='organization.person')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='organization.object')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_donations', to='organization.person')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='organization.currency')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_donations', to='organization.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.person')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.personroletype')),
            ],
        ),
    ]
