# Generated by Django 5.2.5 on 2025-09-27 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address1', models.TextField()),
                ('street_address2', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state_province', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('country', models.TextField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('birth_date', models.DateField()),
                ('db_add_datetime', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.address')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.school')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subjecttype')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.examtype')),
            ],
            options={
                'unique_together': {('subject', 'type')},
            },
        ),
        migrations.CreateModel(
            name='SubjectXStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.person')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subject')),
            ],
            options={
                'unique_together': {('subject', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.TextField(null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.form')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.formfieldtype')),
            ],
            options={
                'unique_together': {('form', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NoteXStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.person')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subjectexam')),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject_x_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subjectxstudent')),
            ],
            options={
                'unique_together': {('subject_x_student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SubjectXTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exa_teachers.person')),
            ],
            options={
                'unique_together': {('subject', 'teacher')},
            },
        ),
    ]
