# Generated by Django 5.2.5 on 2025-09-26 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('related_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organization.person')),
            ],
        ),
    ]
